require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-graphql
# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

Layout/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/Capybara/CurrentPathExpectation:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/FactoryBot/FactoryClassName:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Output:
  Enabled: false

RSpec/Rails/HttpStatus:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

